version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: isguvenligi-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_secure_password}
    
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--requirepass", "${REDIS_PASSWORD:-redis_secure_password}"]
    
    ports:
      - "6379:6379"
    
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_data:/data
      - ./logs/redis:/var/log/redis
    
    networks:
      - isguvenligi-network
    
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
          
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redis_secure_password}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
    restart: unless-stopped
    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: isguvenligi-redis-exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis_secure_password}
    
    ports:
      - "9121:9121"
    
    networks:
      - isguvenligi-network
    
    depends_on:
      redis:
        condition: service_healthy
    
    restart: unless-stopped

volumes:
  redis_data:
    driver: local

networks:
  isguvenligi-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16